version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: smps_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: